In [72]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


dataset = pd.read_csv('insurance.csv')

############################################################
# Finding Duplicated Values using Duplicated() and
# droping the values using dataframe.drop()
############################################################

dup = dataset[dataset.duplicated()].index
print("#"*60 + "\nDuplicated Row....\n" + "#"*60)
print(dup[0])

# Getting the row with duplicated values

print(dataset.iloc[dup])

# Drop the row with duplicated Value
print("#"*60 + "\nDroping The Row 581 ....\n" + "#"*60)
dataset.drop(index=dup, inplace=True)
print(dataset[dataset.columns][579:585])

############################################################
Duplicated Row....
############################################################
581
     age   sex   bmi  children smoker     region  expenses
581   19  male  30.6         0     no  northwest   1639.56
############################################################
Droping The Row 581 ....
############################################################
     age     sex   bmi  children smoker     region  expenses
579   25  female  23.5         0     no  northeast   3206.49
580   59    male  25.5         1     no  northeast  12913.99
582   39    male  45.4         2     no  southeast   6356.27
583   32  female  23.7         1     no  southeast  17626.24
584   19    male  20.7         0     no  southwest   1242.82
585   33  female  28.3         1     no  southeast   4779.60

In [73]:
################################################################
# Converting Categorical Data into Numerical Using LabelEncoder
################################################################

# Gender Col to Numeric
label = LabelEncoder()
label.fit(dataset.sex.drop_duplicates())
dataset.sex = label.transform(dataset.sex)

# Smoker Col to Numeric
label.fit(dataset.smoker.drop_duplicates())
dataset.smoker = label.transform(dataset.smoker)

# Region Col to Numeric
label.fit(dataset.region.drop_duplicates())
dataset.region = label.transform(dataset.region)


dataset.head()

   age  sex   bmi  children  smoker  region  expenses
0   19    0  27.9         0       1       3  16884.92
1   18    1  33.8         1       0       2   1725.55
2   28    1  33.0         3       0       2   4449.46
3   33    1  22.7         0       0       1  21984.47
4   32    1  28.9         0       0       1   3866.86

In [74]:
############################################################
# Splitting Our Dataset into Train and Test Dataset
# Easch Dataset Contain X, and Y for test and Train
# i.e. X_Train, Y_Train, X_Test, Y_Test
############################################################

x = dataset.drop('expenses', axis=1)
y = dataset[['expenses']]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [80]:
############################################################
# Applying Linear Regression Model on Dataset
############################################################

Linear_Model = LinearRegression()
Linear_Model.fit(x_train, y_train)

predict = Linear_Model.predict(x_test)
predict

array([[ 7984.75005493],
       [ 5342.02092418],
       [14384.32080052],
       [31443.58247302],
       [ 9082.70689271],
       [13328.7593392 ],
       [30025.30993737],
       [ 1059.27882197],
       [10789.86922355],
       [11287.46503961],
       [10397.45098694],
       [32904.51010464],
       [30658.58050315],
       [17238.40171068],
       [10645.96776691],
       [ 9213.1706813 ],
       [ 3774.21200256],
       [31641.0601644 ],
       [ 2813.11611359],
       [ 5327.49505716],
       [ 3630.56807153],
       [29861.34171001],
       [15115.66564142],
       [29902.04995935],
       [30838.09654794],
       [ 5396.47271526],
       [35464.92536141],
       [36120.04290472],
       [11295.90458639],
       [14055.39263269],
       [ 6331.53261597],
       [12926.92448838],
       [  413.86598103],
       [11829.57354173],
       [39695.85698723],
       [12083.95405363],
       [ 4313.92823832],
       [ 3805.21058322],
       [30790.42773907],
       [ 9128.11423768],
       [ 6868.07112026],
       [29681.91371966],
       [34712.82325623],
       [12172.90796778],
       [ 7312.47997558],
       [ 3054.89830529],
       [ 6021.21535456],
       [ 8681.67366698],
       [ 4153.38830506],
       [ 9132.32386526],
       [ 6696.44435435],
       [11976.55022695],
       [30865.58594027],
       [ 3616.70492099],
       [10745.97707431],
       [ 9876.58137731],
       [10689.99915001],
       [ 2301.29413577],
       [31078.45192361],
       [ 9358.99120748],
       [15778.61313218],
       [ 8322.46613506],
       [12596.28857657],
       [ 1332.96571322],
       [16770.65826194],
       [10572.24235293],
       [10444.15618502],
       [30224.00909039],
       [24143.52290165],
       [16538.5055243 ],
       [ 7226.71744679],
       [ 2733.02623689],
       [ 6944.88375105],
       [ -273.58671064],
       [11592.22694887],
       [-1534.26975621],
       [16934.40422623],
       [ 8748.56179257],
       [ 7421.34118085],
       [12723.33023946],
       [ 5687.20200281],
       [18768.10975216],
       [15431.2506893 ],
       [11107.47981839],
       [36154.58839648],
       [13334.36554552],
       [ 4163.66734421],
       [ 2380.33202199],
       [ 6479.13580919],
       [ 4147.07601357],
       [15207.33559608],
       [27852.77183277],
       [ 5085.24966021],
       [ 2888.81992855],
       [ 1786.15650967],
       [35587.08752002],
       [14576.49350514],
       [ 8999.16564483],
       [ 4281.91141543],
       [ 8510.05904067],
       [13809.49038214],
       [14895.73042725],
       [32070.64193315],
       [14300.88503825],
       [32465.48713031],
       [  -71.89939167],
       [30725.14433209],
       [26102.3872294 ],
       [13932.58837446],
       [ 5652.37590835],
       [ 8255.32048387],
       [11607.88589783],
       [ 8321.67764137],
       [10086.57498037],
       [ 5848.75075509],
       [ 5462.91228127],
       [ 1820.82061844],
       [ 3112.68416761],
       [ 7145.13079733],
       [ 9178.14356132],
       [36014.935282  ],
       [ 8046.70185089],
       [11737.23371037],
       [ 9293.92195742],
       [ 8985.59622838],
       [ 9333.42936198],
       [ 4200.2699373 ],
       [12144.93229311],
       [29703.8964201 ],
       [38566.26889237],
       [35831.20960963],
       [12180.75256091],
       [ 2426.73354029],
       [11456.6271222 ],
       [10112.70650853],
       [ 5251.69570228],
       [34738.51087895],
       [29473.50175812],
       [25182.29949228],
       [ 4960.98106041],
       [ 6402.21900985],
       [ 5573.24248223],
       [36536.8970651 ],
       [10736.8130194 ],
       [ 5627.18172818],
       [ 8083.61282373],
       [10383.55408815],
       [ 8159.99248657],
       [34975.06897812],
       [14355.65118027],
       [ 9526.13868061],
       [ 6599.78973506],
       [ 6748.43894758],
       [16608.23546761],
       [ 7031.02242245],
       [26265.58160875],
       [36255.27004081],
       [16641.79673173],
       [10074.35280277],
       [11093.08569977],
       [12643.56565121],
       [ 3981.02389962],
       [12838.78433891],
       [13606.589087  ],
       [35500.14821533],
       [32973.48776274],
       [13003.71650231],
       [25011.54828271],
       [ 2369.44709169],
       [ 1761.69500273],
       [ 4798.84483996],
       [ 5125.25050732],
       [ 5047.93349648],
       [ 9918.77326803],
       [10005.82370425],
       [25929.90420696],
       [ 2009.1451924 ],
       [10783.57006345],
       [ 6800.07052959],
       [11983.11288384],
       [14947.23026087],
       [ 5005.99913137],
       [11031.36365234],
       [10066.38959264],
       [32781.55945234],
       [10870.22876544],
       [ 6901.75947865],
       [ 5483.3249573 ],
       [  264.33524098],
       [30989.8354375 ],
       [ 8107.65947351],
       [32476.15544346],
       [12584.9781638 ],
       [ 6083.52618722],
       [ 1508.01460482],
       [ 2081.09542482],
       [32416.76633096],
       [ 4652.72309421],
       [13357.33095931],
       [17450.2479375 ],
       [26038.83934348],
       [25605.98132062],
       [ 6663.38250396],
       [12340.35666046],
       [27875.01803   ],
       [ 7638.59190886],
       [10275.49450797],
       [ 9966.3987082 ],
       [ 3077.65704764],
       [34226.46292989],
       [31029.76832454],
       [ 9564.31946317],
       [ 5916.45363715],
       [ 7579.34767614],
       [10970.82554102],
       [ 4835.11617341],
       [ 5023.6595584 ],
       [11934.33525914],
       [ 9223.33110345],
       [ 2797.50053332],
       [ 4013.54165053],
       [37532.03187189],
       [37097.24630222],
       [13002.0162438 ],
       [10890.09734199],
       [37753.37115026],
       [34089.60198107],
       [ 6910.23277368],
       [26573.30144664],
       [ 3966.56579544],
       [15974.1838936 ],
       [28923.03014656],
       [ 5675.54700179],
       [ 9148.15228539],
       [ 8646.87284351],
       [ 9094.45743365],
       [ 9513.47856875],
       [ 4383.79609843],
       [ 5644.85528661],
       [ 4668.17537173],
       [ 5908.29469307],
       [ 4690.2280289 ],
       [ 5758.27667889],
       [ 8534.65229601],
       [ 1024.16364755],
       [ 8381.78032451],
       [ 3389.999856  ],
       [10605.66721453],
       [ 2442.89190298],
       [10226.72285446],
       [ 3787.2866594 ],
       [11825.86332788],
       [12008.00735874],
       [14411.26609337],
       [36768.0375317 ],
       [22737.08080936],
       [10014.69621897],
       [ 7712.79963067],
       [ 9129.94624459],
       [12381.31992932],
       [29058.314108  ],
       [37888.20655212],
       [14917.61361326],
       [17026.23616659],
       [15530.84016015],
       [ 6241.53268252],
       [38025.2501035 ],
       [ 8171.57256454],
       [ 2077.22322527],
       [ 3009.84151975],
       [14466.04317289],
       [17096.59727202],
       [ 9962.82024274],
       [10097.84918466],
       [12269.90001511],
       [12511.53335251],
       [ 5222.1505257 ],
       [ 9050.57841581],
       [ 1126.77503259],
       [17291.32120012],
       [ 5310.58440925],
       [ 7658.67929644],
       [12274.38029969],
       [ 3129.27549826],
       [13482.93234952],
       [11651.43345881],
       [ 5365.54409133],
       [ 7611.96096696],
       [10578.50530454],
       [10994.07904297],
       [38325.77460809],
       [14117.28514308],
       [ 2159.13913769],
       [-1458.09676481],
       [31253.93378316],
       [11548.32731416],
       [ 2554.96856249],
       [ 9302.38212105],
       [10620.30792126],
       [13355.39028109],
       [ 1139.54282395],
       [ 3075.64243817],
       [39339.29057277],
       [29700.81271425],
       [ 3398.23273133],
       [ 2208.21049647],
       [11031.51250664],
       [ 4171.4248747 ],
       [15923.3283535 ],
       [ 4303.79460144],
       [ 5146.44073955],
       [11365.353927  ],
       [30601.67019716],
       [12793.71541378],
       [25005.0047284 ],
       [ 9640.10417237],
       [ 3243.64736993],
       [ 3062.79972376],
       [30658.67604306],
       [10337.01684693],
       [39001.93001838],
       [ 5157.61940393],
       [10210.19550937],
       [ 6142.45110268],
       [12634.37632531],
       [30681.21597437],
       [11559.27623001],
       [11467.97525774],
       [ 5886.31350692],
       [14250.24982347],
       [ 6155.27074   ],
       [ 8164.08349716],
       [ 7333.06212277],
       [ 4519.23242512],
       [14079.79234798],
       [ 3568.82195521],
       [16156.78961542],
       [ 9640.22994958],
       [12545.56629915],
       [ 5567.07507052],
       [ 5332.13016722],
       [ 4085.35396614],
       [11412.35285918],
       [ 7916.29587945],
       [ 1936.28220336],
       [11646.79834875],
       [32299.50429349],
       [ 8744.94711863],
       [ 5893.02501811],
       [ 6401.84286725],
       [ 3925.33751551],
       [31613.30330077],
       [14924.91410691],
       [25928.2778797 ],
       [35941.77107341],
       [ 5504.92156943],
       [ 8533.98241932],
       [ 8278.04301774],
       [31836.87380574],
       [ 3792.22298902],
       [32546.61454904],
       [27684.58084644],
       [35123.81122447],
       [ 7188.27913862],
       [25993.03277882],
       [ 9865.38209607],
       [13043.68711212],
       [12626.72992635],
       [ 8339.9645764 ],
       [ 9351.2215374 ],
       [11943.54865393],
       [ 5861.54480923],
       [ -892.19814672],
       [11890.3376243 ],
       [ 2610.75294675],
       [ 3525.22354006],
       [18260.18059076],
       [ 5525.44192497],
       [11336.36844152],
       [ 3029.54213942],
       [15026.85561525],
       [10777.63240028],
       [ 2573.75491126],
       [38085.92712343],
       [ 5029.25263333],
       [ 8208.68921704],
       [15863.90303251],
       [15700.56941931],
       [ 9383.32693722],
       [10352.83213567],
       [ 9064.92784868],
       [ -149.94310455],
       [ 9687.21329014],
       [ 4181.53444269],
       [10421.78671667],
       [29217.07288851],
       [ -889.52679196],
       [ 7237.38822017],
       [14095.73938511],
       [12280.92982519],
       [13653.40295639],
       [ 8060.77915834]])

In [90]:
Linear_Model.score(x_test, predict)

1.0

In [88]:
for idx, col_name in enumerate(x_train.columns):
    print(f"the Accuracy of {col_name} is: {Linear_Model.coef_[0][idx]}")

the Accuracy of age is: 252.01037668868634
the Accuracy of sex is: -110.57459517241932
the Accuracy of bmi is: 322.3714821243826
the Accuracy of children is: 524.8966346565155
the Accuracy of smoker is: 22854.786765695324
the Accuracy of region is: -270.6781084529102